### ISSUE TITLE
[14.0] Migrating to Odoo 14

### ISSUE THREAD

**Issue by yboujraf** [Noviat/noviat-apps#2]
Dear @christdum , @luc-demeyer , @marc-pirenne 

Any plan to migrate to Odoo14 ?
Best Regards

**Comment by luc-demeyer** [comment]
migration is in process and several modules are already in alpha testing at a pilot customer.
Which of the modules are you looking for ?

**Comment by yboujraf** [comment]
Dear @luc-demeyer 

Thanks for your reply.

Today I am using Odoo8 with most of your modules for Belgian accounting.
- Chart of accounts, chart of taxes, VAT declaration & intrastat & customer list, coda file import, BBA, all regarding Belgian accounting.

Now we decided to migrate to Odoo 14 or Maybe Odoo13 if there is no really difference or enhancement for accounting purpose.

I tried to add the repository [branh - 13.0] to our /odoo/custom/addons but lot of dependencies are missing.
Thanks if you could highlight me how to force the dependencies to be installed

Best Regards,

**Comment by luc-demeyer** [comment]
There are still a couple of bugs in our 14.0 port of the accounting modules but nothing major (should be fixed by the end of this month) and the bugs are only in the area of ‘ease of configuration’ hence you could already run them in production (which our current alfa customer does).

If you want to migrate from 8 to 14 than you’ll probably face an issue since the community migration scripts still need to become mature.
When uggrading today I would recommend to move to Odoo 13 unless you want to drop all transaction history and start with a fresh database. In that case I can give you access to the 14.0 'alfa' port. You can contact me offline (luc.demeyer@noviat.com) to set this up.

**Comment by yboujraf** [comment]
Dear @luc-demeyer 

I have sent you an email.

Let me know if yoi received.

Best regards

**Comment by yboujraf** [comment]
Thank for your reply.
Best Regards
